- hosts: compute
  remote_user: root
  tasks:
    - name: remove current repo
      file:
        path: "{{item}}"
        state: absent
      with_fileglob:
        - /etc/yum.repos.d/*.repo
      retries: 10
      delay: 5

    - name: Add repository
      yum_repository:
        name: yeecloud
        description: add yeecloud repo
        baseurl: http://192.168.16.111/centos73/
        enabled: yes
        gpgcheck: no
    - name: make cache
      command: yum makecache

    - name: nova package
      yum: pkg={{item}} state=installed
      with_items:
        - openstack-nova-compute
    - name: Config the nova
      ini_file:
        dest: /etc/nova/nova.conf
        section: DEFAULT
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      with_items:
        - { option: enabled_apis , value: osapi_compute,metadata}
        - { option: transport_url , value: "rabbit://openstack:admin@controller"}
        - { option: my_ip, value: "{{ansible_default_ipv4.address}}"}
        - { option: use_neutron, value: True}
        - { option: firewall_driver, value: nova.virt.firewall.NoopFirewallDriver}

    - name: Config the nova api auth
      ini_file:
        dest: /etc/nova/nova.conf
        section: api
        option: auth_strategy
        value: keystone

    - name: Config the nova api keystone authtoken
      ini_file:
        dest: /etc/nova/nova.conf
        section: keystone_authtoken
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      with_items:
        - { option: auth_uri, value: "http://controller:5000"}
        - { option: auth_url, value: "http://controller:35357"}
        - { option: memcached_servers, value: "controller:11211"}
        - { option: auth_type, value: password}
        - { option: project_domain_name, value: default }
        - { option: user_domain_name, value: default }
        - { option: project_name, value: service }
        - { option: username, value: nova }
        - { option: password, value: admin }

    - name: Config the nova vnc
      ini_file:
        dest: /etc/nova/nova.conf
        section: vnc
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      with_items:
        - { option: enabled, value: true}
        - { option: vncserver_listen , value: "$my_ip"}
        - { option: vncserver_proxyclient_address , value: "$my_ip"}
        - { option: novncproxy_base_url , value: "http://controller:6080/vnc_auto.html"}

    - name: Config the nova glance
      ini_file:
        dest: /etc/nova/nova.conf
        section: glance
        option: api_servers
        value: "http://controller:9292"
    - name: Config oslo concurrency
      ini_file:
        dest: /etc/nova/nova.conf
        section: oslo_concurrency
        option: lock_path
        value: /var/lib/nova/tmp
    - name: Config virt
      ini_file:
        dest: /etc/nova/nova.conf
        section: libvirt
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      with_items:
        - { option: virt_type , value: qemu}
        - { option: cpu_mode , value: none}
 

    - name: Config the nova placement
      ini_file:
        dest: /etc/nova/nova.conf
        section: placement
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      with_items:
        - { option: os_region_name , value: RegionOne}
        - { option: project_domain_name , value: Default}
        - { option: project_name , value: service}
        - { option: auth_type, value: password}
        - { option: project_domain_name, value: Default }
        - { option: user_domain_name, value: Default }
        - { option: project_name, value: service }
        - { option: username, value: placement }
        - { option: password, value: admin }
        - { option: auth_url, value: "http://controller:35357/v3" }

    - name: Config the nova api keystone authtoken
      ini_file:
        dest: /etc/nova/nova.conf
        section: neutron
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      with_items:
        - { option: os_region_name , value: RegionOne}
        - { option: project_domain_name , value: Default}
        - { option: project_name , value: service}
        - { option: auth_type, value: password}
        - { option: project_domain_name, value: Default }
        - { option: user_domain_name, value: Default }
        - { option: project_name, value: service }
        - { option: username, value: neutron }
        - { option: password, value: admin }
        - { option: auth_url, value: "http://controller:35357/v3" }


    - name: retstart nova
      service:
        name: "{{item}}"
        enabled: yes
        state: restarted
      with_items:
        - libvirtd
        - openstack-nova-compute

