- hosts: all
  remote_user: root
  tasks:
    - name: change host name
      hostname:
        name: "{{inventory_hostname}}"
    - name: set hosts
      copy:
        src: "{{ hosts_file }}"
        dest: /etc/hosts
    - name: stop firewalld
      service:
        name: firewalld
        enabled: no
        state: stopped

    - name: iptables flush
      command: "{{item}}"
      with_items:
        - iptables -F
        - setenforce 0
      ignore_errors: True

      become: yes
    - name: change host name
      hostname:
        name: "{{inventory_hostname}}"
    - name: remove current repo
      file:
        path: "{{item}}"
        state: absent
      with_fileglob:
        - /etc/yum.repos.d/*.repo
      retries: 10
      delay: 5


    - name: Add repository
      yum_repository:
        name: yeecloud
        description: add yeecloud repo
        baseurl: http://192.168.16.111/centos73/
        enabled: yes
        gpgcheck: no
    - name: yum make cache
      command: yum makecache
#     - name: upgrade
#       yum: name=*
#            state=latest
    - name: off selinux
      selinux:
        state: disabled
#     - name: Restart server
#       command: /sbin/shutdown -r +1
#       async: 0
#       poll: 0
#       ignore_errors: true

#    - name: wait for server restart
#      local_action:
#        module: wait_for
#          host=controller
#          port=22
#          delay=61
#          timeout=600
#      ignore_erros: true

