- hosts: all
  remote_user: root
  tasks:
    - name: change host name
      hostname:
        name: "{{inventory_hostname}}"
    - name: set hosts
      copy:
        src: /etc/hosts
        dest: /etc/hosts

    - name: remove current repo
      file:
        path: "{{item}}"
        state: absent
      with_fileglob:
        - /etc/yum.repos.d/*.repo

    - name: Add repository
      yum_repository:
        name: yeecloud
        description: add yeecloud repo
        baseurl: http://192.168.16.111/centos73/
        enabled: yes
        gpgcheck: no
    - name: yum make cache
      command: yum makecache
